name: Test
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
          - 18
          - 16
    name: Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        # Pulls version from packageManager key in package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
      - name: Run unit tests
        run: pnpm test
